print("Welcome to  the tip calculator!")
total_bill = float(input("What was the total bill? $"))
tip_percentage = int(input("How much tip would you like to give? 10, 12 or 15? "))
people_splitting_the_bill = int(input("How many people to split the bill? "))
bill_per_person = round((total_bill+total_bill*tip_percentage/100)/people_splitting_the_bill,2)
print(f"Each person should pay: ${bill_per_person}")
